import type { Ui } from './strings';

/** English UI strings. Same keys and signatures as the Russian dictionary in `strings.ts` (checked by the compiler). */
const pl = (n: number, one: string, many: string): string => (n === 1 ? one : many);

export const en: Ui = {
  hud: {
    aria: 'Session',
    sessions: 'sessions',
    sessionsTitle: 'Sessions',
    untitled: 'new session',
  },
  tabs: { chat: 'chat', changes: 'changes', git: 'git', agents: 'agents' },
  panel: {
    tabsAria: 'Panel: changes, git, agents',
    hide: 'Hide panel',
    show: 'Show panel',
    railAria: 'Collapsed panel',
    openTab: (name: string) => `Open panel: ${name}`,
    gripAria: 'Panel width',
    gripTitle: 'Drag to resize; double-click for 300 px',
  },
  log: {
    aria: 'Session feed',
    diff: 'diff',
    preview: 'preview',
    open: 'open',
    artifactCreated: 'created',
    artifactUpdated: 'updated',
    artifactPublished: 'published',
    stop: 'stop · esc',
    stopOnly: 'stop',
    stopTip: 'Stop the turn',
    copy: 'copy',
    copied: 'copied',
    queued: 'queued',
    thinking: 'thinking',
    answering: 'answering',
    waiting: 'waiting for a reply',
    waitingPlan: 'waiting for a plan decision',
    compacting: 'compacting context',
    waitingPermission: 'waiting for permission',
    running: (op: string) => `running ${op}`,
    toolError: 'error',
    toolStopped: 'stopped',
    thinkToggle: 'Show full reasoning',
    actions: (n: number) => `${n} ${pl(n, 'action', 'actions')}`,
    foldLive: 'running',
    foldToggle: 'Show or hide the turn actions',
    turnLive: (t: string) => `running ${t}`,
    who: 'claude',
    waitingAgents: (n: number) => `waiting for ${n} ${pl(n, 'agent', 'agents')}`,
    stopAll: 'stop all · esc',
    stopAllTitle: 'Stop all running subagents of the session (Esc interrupts the whole turn)',
    imagesTokens: (k: string) => `images ≈${k}`,
    imagesTokensTitle:
      'Estimated from image size: width × height / 750 (the engine does not count them separately)',
    screenshot: 'screenshot',
    openImage: 'Open the image in an editor tab',
    noImageData:
      'The transcript has no image data (or it is older than the latest in history) — placeholder only',
    openFile: 'Open the file in an editor tab',
    inPath: (path: string) => `in ${path}`,
    todoWhat: 'to-do list',
    askFallback: 'question',
    planReady: 'plan ready',
    fileNoCopy:
      'The file is outside the workspace and there is no copy in history (older than the latest) — the original opens if it is still there',
  },
  sys: {
    compacting: 'compacting context…',
    compactedAuto: 'context compacted automatically',
    compactedManual: 'context compacted',
    compactFailed: (error?: string) => `could not compact context${error ? `: ${error}` : ''}`,
    interrupted: 'turn interrupted',
    tokensSuffix: ' tokens',
    closed: (reason: 'exit' | 'error' | 'disposed', message?: string) =>
      reason === 'error'
        ? `session dropped${message ? `: ${message}` : ''}`
        : reason === 'exit'
          ? 'engine exited, session closed'
          : 'session closed',
    status: (model: string, mode: string, cwd: string) =>
      `/status · model ${model} · mode ${mode} · ${cwd}`,
    planOn: 'plan mode on',
    contextPassed: (used: string, threshold: string, fullAt: string) =>
      `context ${used}: passed the ${threshold} threshold, auto-compact at ${fullAt}`,
    historyTrimmed: (n: number) =>
      `showing the latest turns; ${n} earlier ${pl(n, 'turn', 'turns')} not shown`,
    sendFailed: 'message not sent: the session has ended',
    modeChanged: (mode: string) => `mode: ${mode}`,
    turnNotStarted: (message: string) => `turn did not start: ${message}`,
    limitDefault: 'limit reached',
    resetAt: (time: string) => `resets at ${time}`,
    denied: 'denied: ',
    alwaysRule: 'always: ',
    questionDeclined: 'question declined',
    picked: (nums: number[]) =>
      nums.length === 1
        ? `picked option ${nums[0]}`
        : nums.length > 1
          ? `picked options ${nums.join(', ')}`
          : 'answer sent',
    customAnswer: (text: string) => `custom answer: ${text}`,
    plan: {
      run: 'plan accepted · running',
      'run-edits': 'plan accepted · running, accepting edits',
      refine: 'plan sent back for changes',
      reject: 'plan rejected',
    },
  },
  fail: {
    titleFatal: 'Engine stopped',
    titleTurn: 'Turn failed',
    tag: (at: string) => `${at} · error`,
    codeLine: (code: string) => `error code: ${code}`,
    hintNetwork:
      'Looks like a network drop. The session is saved: on retry the turn restarts with the same message.',
    hintTurn: 'The session is saved: on retry the turn restarts with the same message.',
    hintIdle: 'The session is saved: you can resume it and continue.',
    retryTurn: 'Retry turn',
    retryResume: 'Resume session',
    retrying: 'retrying…',
    missingTitle: 'Claude Code not found',
    missingHint:
      'Install Claude Code (https://claude.com/claude-code), sign in (claude → /login) or set the path to claude in settings ⚙ (agentura.claudeExecutable).',
    missingSettings: 'Open settings',
    missingRecheck: 'Check again',
    missingChecking: 'checking…',
    openLog: 'Open extension log',
    logHint: 'log: Output panel → Agentura',
    toolOutputTitle: 'Tool output',
    toolOutputHint: 'Full output, as the model saw it.',
    toolToggle: 'Show full output',
    toolFailTag: 'tool result',
    truncated: (n: number) => `… ${n} more ${pl(n, 'character', 'characters')} truncated`,
  },
  limit: {
    bannerFive: '5-hour window limit reached.',
    bannerWeek: 'Weekly limit reached.',
    bannerWeekModel: (model: string) => `Weekly limit for ${model} reached.`,
    bannerGeneric: 'Subscription limit reached.',
    resetsAt: (time: string, left: string) => `Resets at ${time}, in ${left}.`,
    resetUnknown: 'Reset time unknown.',
    weekFree: (percent: number) => `Weekly window is ${percent}% free.`,
    limits: 'Limits',
    limitsTitle: 'Open the sidebar with limits',
    retry: 'Try again',
    retryTitle: 'Unblock and send the message: the limit may have reset',
    deferred: (time: string) => `sending deferred until ${time}`,
    deferredUnknown: 'sending deferred: limit reached',
    placeholder: 'limit reached — you can type a message, it is sent after the reset',
  },
  cards: {
    permTitle: (tool: string) =>
      tool === 'Bash'
        ? 'Allow running this command?'
        : tool === 'Edit' || tool === 'MultiEdit'
          ? 'Allow editing this file?'
          : tool === 'Write'
            ? 'Allow writing this file?'
            : `Allow ${tool}?`,
    modeTag: (mode: string) => `mode ${mode}`,
    subagent: 'subagent',
    allow: 'Allow',
    acceptEdit: 'Accept edit',
    alwaysFor: 'Always for',
    alwaysDirs: 'Always for folder',
    acceptEditsSession: 'Accept edits for the rest of the session',
    deny: 'Deny',
    sent: 'answer sent…',
    enter: 'enter',
    esc: 'esc',
    destination: (d?: string) =>
      d === 'localSettings'
        ? '.claude/settings.local.json'
        : d === 'projectSettings'
          ? '.claude/settings.json'
          : d === 'userSettings'
            ? '~/.claude/settings.json'
            : 'this session',
    alwaysHint: (where: string) => `“always” is written to ${where}`,
    sessionHint: '“always” lasts until the end of the session',
    plusDirs: (dir: string, more: number) =>
      ` · and folder ${dir}${more > 0 ? ` +${more}` : ''} until the end of the session`,
    editsHint: '“accept edits” = acceptEdits mode',
    workdir: (dir: string) => `working folder ${dir}`,
    blocked: (path: string) => `outside allowed folders: ${path}`,
    openDiff: 'open diff',
    newFile: 'new file',
    diffNote: 'The full diff opens in the VS Code editor.',
    fragmentNote: 'The fragment was not found in the file on disk — showing the edit itself.',
    tooLarge: 'The diff is too large to preview — open it in the editor.',
    moreLines: (n: number) => `… ${n} more ${pl(n, 'line', 'lines')} — in the full diff`,
    previewLoading: 'preparing preview…',
    question: 'agent question',
    questionAnswered: 'agent question · answered',
    questionDeclined: 'agent question · declined',
    questionCancelled: 'agent question · cancelled',
    multi: 'multiple allowed',
    custom: 'Custom option',
    customHint: 'I will type it in the input field',
    submit: 'Reply',
    planTitle: 'Plan',
    planTag: (steps: number, files: number) =>
      [
        steps ? `${steps} ${pl(steps, 'step', 'steps')}` : '',
        files ? `${files} ${pl(files, 'file', 'files')}` : '',
      ]
        .filter(Boolean)
        .join(' · ') || 'plan',
    planDone: {
      run: 'plan · accepted',
      'run-edits': 'plan · accepted, edits without prompts',
      refine: 'plan · sent back for changes',
      reject: 'plan · rejected',
    },
    planCancelled: 'plan · cancelled',
    run: 'Run',
    runEdits: 'Run, accepting edits',
    refine: 'Refine plan',
    reject: 'Reject',
    planFileNew: 'new',
    planFileEdit: 'edit',
  },
  reply: {
    question: 'your own answer to the agent’s question — enter · esc to cancel',
    plan: 'what to change in the plan — enter · esc to cancel',
    waiting: 'reply to the agent or a new task — sent after the request is resolved',
  },
  empty: {
    title: (project: string) => `New session in ${project}`,
    lead: 'Describe a task or ask a question. The agent sees the open file and selection — remove them with the cross next to the input.',
    tips: [
      ['@', 'project files and folders'],
      ['/', 'commands and skills: /plan, /compact, /status'],
      ['shift+enter', 'new line'],
      ['esc', 'stop the turn'],
      ['↑', 'previous messages'],
    ],
    recent: 'recent sessions',
    newSession: 'new session',
    turns: (n: number) => `${n} ${pl(n, 'turn', 'turns')}`,
    waiting: 'waiting for a reply',
  },
  agents: {
    heading: 'agents',
    stopTitle: 'Stop',
    empty: 'nothing yet',
    main: 'main',
    waitingTask: 'waiting for a task',
    answering: 'answering',
    background: 'background task',
    done: 'done',
    failed: 'error',
    stopped: 'stopped',
    totalCost: 'this session',
    costPartial: '≈ excluding some turns',
    totalTurns: 'turns',
    totalTime: 'time',
    totalCache: 'cache hits',
    waitingAgents: 'waiting for agents',
    turnDone: 'turn finished',
    running: 'running',
    tasks: 'background tasks',
    bar: 'turn tokens by agent',
    turnTokens: 'subagents this turn',
    shell: 'shell',
    finishedAt: (time: string) => `finished ${time}`,
    starting: 'starting',
    thinking: 'thinking',
    writing: 'writing the summary',
    nthCall: (n: number) => `call #${n}`,
    doneIn: (d: string) => `done in ${d}`,
    group: {
      parallel: (n: number) => `×${n} in parallel`,
      single: 'subagent',
      running: (n: number) => `${n} running`,
      done: (n: number) => `${n} done`,
      failed: (n: number) => `${n} ${pl(n, 'error', 'errors')}`,
      stopped: (n: number) => `${n} stopped`,
      tokens: 'tok',
      background: 'in background',
      map: 'agent map',
      waiting: 'main is waiting for agents',
      collapse: 'collapse',
      summary: 'summary',
      log: 'log',
      stop: 'Stop agent',
      more: (n: number) => ` +${n}`,
    },
    // roadmap 11: panel views (tree, lanes, cards)
    view: {
      scopeAria: 'Scope',
      scopeTurn: (n: number) => `turn ${n}`,
      scopeTurnNone: 'turn',
      scopeSession: 'session',
      graph: '↗ graph',
      graphTitle: 'Open the agents graph in an editor tab',
      empty: 'No agents in this session yet',
      turnTitle: (n: number) => `turn ${n}`,
      toggleTurn: 'Show or hide the turn',
      live: (d: string) => `running ${d}`,
      done: 'finished',
      agentsTokens: 'agents',
      mainAt: (ctx: string) => `context ${ctx}`,
      promptLabel: (est: string) => `prompt from main · ${est}`,
      summaryLabel: (est: string) => `summary · ${est}`,
      errorLabel: 'error',
      callsLabel: (n: number) => `latest calls · ${n}`,
      estTip: 'estimated from the text length',
      transcript: 'transcript',
      log: 'log',
      stop: 'stop',
      stopShort: '■ stop',
      calls: (n: number) => `${n} ${pl(n, 'call', 'calls')}`,
      resultToMain: (est: string) => `summary ${est} → to main`,
      bg: 'background',
      sinceTurn: (n: number) => `since turn ${n}`,
      shellKind: 'shell',
      before: '↤ before the axis',
      axisAria: 'Turn time axis',
      nowAria: 'now',
      wait: 'waiting for agents',
      counts: {
        running: (n: number) => `${n} running`,
        ok: (n: number) => `${n} done`,
        err: (n: number) => `${n} ${pl(n, 'error', 'errors')}`,
        stop: (n: number) => `${n} stopped`,
      },
    },
    graph: {
      aria: 'Agents graph',
      turn: 'turn',
      turnsAria: 'Turns with agents',
      live: 'running',
      agentsTotal: 'agents',
      context: (used: string, limit: string) => `context ${used} / ${limit}`,
      returned: (est: string) => `summaries returned: ${est}`,
      edgeTip: '↗ prompt to the agent (estimated by length) · ↙ summary back to the main agent',
      legendUp: '↗ prompt to agent',
      legendDown: '↙ summary to main',
      legendBg: 'dashed — background',
      summaryPending: 'summary · appears when the agent finishes',
      waiting: 'Waiting for data from the chat tab — if it is hidden, bring it up.',
      pick: 'Pick an agent on the graph',
      detailAria: 'Selected agent',
    },
    detail: {
      prompt: 'prompt from main',
      summary: 'summary for main',
      error: 'error',
      stoppedNote: 'agent stopped',
      timeline: (n: number) => `agent turn · ${n} ${pl(n, 'call', 'calls')}`,
      more: (n: number) => `${n} more ${pl(n, 'line', 'lines')}`,
      empty: 'no calls yet',
      text: 'text',
      transcript: 'transcript',
      transcriptTitle: 'Open the agent transcript (read-only)',
      stop: 'stop',
      tokens: 'tokens',
      calls: 'calls',
      live: (d: string) => `◐ running ${d}`,
      ok: (d: string) => `✓ done in ${d}`,
      err: (d: string) => `✕ error · ${d}`,
      stopped: (d: string) => `■ stopped · ${d}`,
    },
  },
  changes: {
    scopeAria: 'Scope',
    session: 'session',
    turn: (n: number) => `turn ${n}`,
    files: (n: number) => pl(n, 'file', 'files'),
    diffAll: 'diff all',
    diffAllTitle: 'Open the diff of all changed files',
    fileTitle: 'Open the file diff',
    root: './',
    newFile: 'new',
    checks: 'checks',
    emptySession: 'The agent has not changed anything yet',
    emptyTurn: 'No edits in this turn',
    turnTitle: (n: number) => `Turn ${n}`,
  },
  git: {
    loading: 'git is loading…',
    none: 'No repositories',
    noneHint:
      'VS Code looks for repositories up to git.repositoryScanMaxDepth levels deep (1 by default); open a repository folder or raise the value.',
    unavailable: 'git is unavailable',
    changes: (n: number) => `${n} ${pl(n, 'change', 'changes')}`,
    repos: (n: number) => `${n} ${pl(n, 'repository', 'repositories')}`,
    agentChip: (n: number) => `agent ${n}`,
    agentChipTitle: 'Show only the files the agent edited',
    modeAria: 'List view',
    modePath: 'path',
    modeTree: 'tree',
    unstaged: 'unstaged',
    staged: 'staged',
    stageAll: '+ stage all',
    unstageAll: '− all',
    emptyUnstaged: 'none',
    emptyStaged: 'empty — use “+” on a file',
    emptyAgent: 'no agent files',
    clean: 'clean',
    recent: 'recent commits',
    branchTitle: 'Switch branch',
    unpublished: 'not published',
    unpublishedTitle: 'The branch is not on the remote — push will publish it',
    syncTitle: (up: string) => `Against ${up}`,
    fetch: 'Fetch',
    pull: 'Pull',
    push: 'Push',
    publish: 'Publish branch',
    agentDot: 'Edited by the agent in this session',
    openFile: 'Open file',
    discard: 'Discard changes',
    stage: 'Stage',
    unstage: 'Unstage',
    openDiff: 'Open diff',
    renamedFrom: (from: string) => `from ${from}`,
    binary: 'bin',
    statusTitle: {
      M: 'modified',
      A: 'added',
      D: 'deleted',
      R: 'renamed',
      U: 'untracked',
      C: 'conflict',
      T: 'type changed',
    },
    op: { merge: 'merge in progress', rebase: 'rebase in progress' },
    summaryPlaceholder: 'Commit message',
    summaryAria: 'Commit summary',
    descPlaceholder: 'Description',
    descAria: 'Commit description',
    generate: 'The agent writes the message from the index',
    generateSoon: 'Soon: the agent will write the commit message',
    amend: 'amend',
    andPush: 'and push',
    commit: 'Commit',
    filesN: (n: number) => `${n} ${pl(n, 'file', 'files')}`,
    commitAmend: 'Amend',
    commitHint: '⌘/Ctrl+Enter',
    needStage: 'Stage files first',
    needMessage: 'Enter a commit summary',
    busy: 'Operation in progress…',
    more: 'More',
    commitPush: 'Commit and push',
    commitAll: 'Commit all changes',
    errorClose: 'Dismiss',
    errorOp: (op: string, message: string) => `${op}: ${message}`,
  },
  compose: {
    mode: 'mode',
    model: 'model',
    effort: 'effort',
    agent: 'agent',
    agentTitle: 'Agent: Claude · Codex, Gemini — coming soon',
    context: 'context',
    compact: 'compact',
    ctxTitle: (thresholds: string[], fullAt: string, scale?: string) =>
      `Context: thresholds ${thresholds.join(' ')}, auto-compact at ${fullAt}${scale ? ` · scale up to ${scale}` : ''}`,
    thresholdPassed: (k: string) => `passed ${k}`,
    cache: 'cache',
    cacheExpired: 'expired',
    cacheTitle: (ttl: string) => `Prompt cache: lives ${ttl} after the last reply`,
    fiveHour: '5h',
    fiveHourWindow: '5-hour window',
    week: 'week',
    weekShort: 'wk',
    limitsUnknown: 'Subscription limits not received yet',
    send: 'enter ↵',
    sendTitle: 'Send',
    placeholder: 'task, @file, /command',
    closedPlaceholder: 'session ended — start a new one with “+ New session” in the sidebar',
    plus: '+',
    plusTitle: 'Add context',
    removeChip: 'Remove from context',
    autoFile: 'open',
    autoSelection: 'selection',
    historyPos: (i: number, n: number) => `${i} of ${n}`,
    historyNote: '· ↑ older · ↓ newer · esc to clear',
    historyLabel: 'history',
    agentMenu: 'agent',
    agentReady: 'ready',
    claudeVia: (version?: string) => `via Claude Agent SDK${version ? ` · claude ${version}` : ''}`,
    acpAdapter: 'ACP-shaped adapter',
    agentSoon: 'soon',
    imagesHint: '⌘V — paste an image · drag with ⇧',
    imagesPlus: (k: string) => `+${k} images`,
    imagesPlusTitle: 'Images are counted by size: width × height / 750 tokens',
    imageName: (n: number) => `screenshot ${n}`,
    imageBusy: 'scaling down…',
    imageScaled: (w: number, h: number) => `scaled down from ${w}×${h}`,
    imageRemove: 'Remove',
    imageFormats: 'supported: png, jpeg, gif, webp',
    imageProblem: {
      format: (ext: string) => `${ext || 'this format'} is not supported`,
      size: 'over 5 MB',
      count: 'up to 10 images',
      total: 'message over 20 MB',
      read: 'cannot read',
      session: 'session: attachments over 24 MB — start a new one',
      context: 'will not fit the model window',
    },
    imageProblemTitle: {
      format: 'supported: png, jpeg, gif, webp',
      size: 'even after scaling down to 1568 px the image is still over 5 MB in base64',
      count: 'up to 10 images per message',
      total:
        'images of one message — up to 20 MB of base64 together (the API request limit is 32 MB)',
      read: 'the file could not be read or is corrupted',
      session:
        'The API request limit is 32 MB, and every request carries the whole history with its attachments: this session already has too many. “Compact” removes old attachments from requests, a new session starts from scratch',
      context:
        'Message attachments can take at most 70% of the free context window; “compact” will free up space',
    },
    filesHint: 'drag with ⇧ — a file from the VS Code explorer',
    filesPlus: (k: string) => `+${k} files`,
    filesPlusTitle: 'Estimate: text — characters / 4, pdf — about 1,500 tokens per page',
    fileUnknownTokens: '≈?',
    fileProblem: {
      binary: 'binary files are not supported',
      size: 'too large',
      empty: 'empty file',
      folder: 'folders are not supported',
      pages: 'over 100 pages',
      read: 'cannot read',
      count: 'up to 10 files',
      total: 'message over 20 MB',
      foreign: 'not an image — use “+”',
      pdf: 'pdf cannot be read',
      sessionPages: 'session: pdf over 100 pages — start a new one',
      session: 'session: attachments over 24 MB — start a new one',
      context: 'will not fit the model window',
    },
    fileProblemTitle: {
      binary: 'supported: UTF-8 text (no NUL bytes), pdf and png, jpeg, gif, webp images',
      size: 'text — up to 256 KB, pdf — up to 15 MB, any file — up to 30 MB',
      empty: 'the file has no text',
      folder: 'drag the files from the folder, not the folder itself',
      pages: 'the API accepts pdf up to 100 pages',
      read: 'the file could not be read',
      count: 'up to 10 files per message',
      total:
        'images and files of one message — up to 20 MB together (the API request limit is 32 MB)',
      foreign:
        'Only images can be dragged in from outside VS Code: add text and pdf with “+” or drag them from the VS Code explorer',
      pdf: 'the pdf is encrypted, corrupted or has no pages — the API would reject it, and the rejection would stay in the session',
      sessionPages:
        'The API limit is 100 pdf pages per request, and every request carries the whole session history: with this pdf there would be more. “Compact” removes old attachments from requests, a new session starts from scratch',
      session:
        'The API request limit is 32 MB, and every request carries the whole history with its attachments: this session already has too many. “Compact” removes old attachments from requests, a new session starts from scratch',
      context:
        'Message attachments can take at most 70% of the free context window (text — characters / 4, pdf — about 1,500 tokens per page); “compact” will free up space',
    },
  },
  menus: {
    commands: 'commands',
    skills: 'project skills',
    files: 'files and folders',
    noFiles: 'nothing found',
    fileHint: 'file',
    folderHint: 'folder',
    skillHint: 'skill',
    addContext: 'add context',
    pickFile: 'File or folder…',
    pickFileHint: '@',
    openFile: 'Open file',
    selection: 'Editor selection',
    autoOn: 'added automatically',
    autoOff: 'not added',
    image: 'Image or file…',
    imageSmall: 'text, pdf, image · ⌘V — screenshot, drag with ⇧',
    imageHint: '⌘V',
    mode: 'mode',
    model: 'model',
    effort: 'effort',
    thinking: 'extended thinking',
    thinkingHint: 'show think blocks in the feed',
    byDefault: 'default',
    bypassOff: 'enabled by the agentura.allowBypassPermissions setting',
    modelDesc: {
      opus: 'complex tasks, planning',
      sonnet: 'faster and cheaper',
      haiku: 'small edits',
    },
  },
  commands: {
    plan: ['switch to plan mode', 'mode'],
    compact: ['compact context now', 'context'],
    clear: ['new conversation', '⌘N'],
    status: ['account, login, model', ''],
  },
  modes: {
    default: ['manual', 'ask before edits and commands', ''],
    acceptEdits: [
      'accept edits',
      'file edits without prompts, commands with a prompt',
      'acceptEdits',
    ],
    plan: ['plan', 'read and plan only', '/plan'],
    bypassPermissions: ['no permissions', 'no prompts at all', 'bypass'],
  },
  efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
  time: {
    weekdaysShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    weekdaysLong: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    months: [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ],
    dayMonth: (day: number, month: number, year?: number): string =>
      `${en.time.months[month]} ${day}${year !== undefined ? `, ${year}` : ''}`,
    lessThanMinute: 'less than a minute',
    minutes: (n: number) => `${n} min`,
    hourMinutes: (h: number, mm: string) => `${h} h ${mm} min`,
    daysHours: (d: number, h: number) => `${d} d ${h} h`,
    oneHour: '1 h',
    at: (clock: string) => `at ${clock}`,
    atWeekday: (weekday: string, clock: string) => `on ${weekday}, ${clock}`,
    atDate: (date: string, clock: string) => `${date}, ${clock}`,
  },
  settings: {
    title: 'Settings',
    head: 'Agentura · Settings',
    aria: 'Settings',
    openUi: 'in VS Code settings',
    openUiTitle: 'Open in VS Code settings',
    openJson: 'settings.json',
    openJsonTitle: 'Open settings.json',
    openJsonLink: 'open settings.json',
    navAria: 'Settings sections',
    sections: {
      session: 'New session',
      limits: 'Context and limits',
      sidebar: 'Sidebar',
      look: 'Appearance',
      engine: 'Engine',
    },
    source: 'Stored in VS Code settings, “User” scope. Applied immediately, no restart needed.',
    isNew: 'new',
    machineOnly: 'this machine only',
    overridden:
      'This value is overridden in the workspace settings — you are editing the user value here; it takes effect once the override is removed.',
    mode: {
      name: 'New session mode',
      desc: 'The mode a new session opens with. In an open session, change the mode with the “mode” menu under the input or with ⇧⇥.',
      options: {
        manual: 'manual',
        acceptEdits: 'acceptEdits',
        plan: 'plan',
        bypassPermissions: 'no permissions',
      },
    },
    bypass: {
      name: 'Allow “no permissions” mode',
      desc: 'Adds the “no permissions” item (bypassPermissions) to the mode menu. It does not turn the mode on — you pick it in a session.',
      warnTitle: 'No permissions',
      warn: ' the agent edits files and runs any commands without asking — including deletion and network access. Enable it for an isolated folder or a container; on a working project, “accept edits” is safer.',
    },
    model: {
      name: 'Default model',
      desc: 'For new sessions. Empty — the one set in Claude Code (engine’s choice).',
      placeholder: 'engine’s choice',
    },
    effort: {
      name: 'Default effort',
      desc: 'How much to think before replying. Changed in the row under the input.',
      engine: 'engine’s choice',
    },
    thresholds: {
      name: 'Context gauge thresholds',
      desc: 'Where the bar and the number above the input turn yellow and orange. Auto-compact at 200,000 is done by the engine — not configurable here.',
      yellow: 'yellow',
      orange: 'orange',
      compress: '200k · compact',
    },
    poll: {
      name: 'Poll limits every',
      desc: '5-hour and weekly window in the sidebar and under the input. Manually — ↻ in the sidebar.',
      noLess: 'at least 5',
      unit: 'min',
    },
    listView: {
      name: 'Session list view',
      desc: 'How many lines per session in the sidebar. Turns and cost are always in the row tooltip. Also switched by the button in the “Sessions” header.',
      options: {
        detailed: 'detailed — two lines',
        compact: 'compact — two lines only for important ones',
        dense: 'dense — everything on one line',
      },
    },
    listContext: {
      name: 'Context in the row',
      desc: 'Right column: the context of the session’s last request, e.g. 173k ctx.',
    },
    listTime: {
      name: 'Time in the row',
      desc: 'Right column: when the session was updated — now, 13:05, Tue, 25.09.',
    },
    language: {
      name: 'Interface language',
      desc: 'Applied after the VS Code window reloads. “Same as VS Code” — Russian if VS Code is in Russian, otherwise English. Command titles and setting descriptions always follow the VS Code language.',
      options: {
        auto: 'Same as VS Code',
        ru: 'Русский',
        en: 'English',
      },
    },
    sidebarTop: {
      name: 'Sidebar top',
      desc: 'How much space the account and limits take: detailed — a table, compact — a line each, dense — mini limit gauges in the panel header.',
      options: {
        detailed: 'detailed — as before',
        compact: 'compact — account and limits on one line each',
        dense: 'dense — limits in the panel header',
      },
    },
    feedStyle: {
      name: 'Chat feed style',
      desc: 'How a turn looks: journal — a flat list, folded — finished turns collapse their actions into one line, replies — a bubble and action chips, cards — a turn as a framed card with a timeline. Open tabs switch immediately.',
      options: {
        journal: 'journal — as before',
        folded: 'folded — actions on one line',
        replies: 'replies — bubble and chips',
        cards: 'cards — a turn in a frame',
      },
    },
    agentsView: {
      name: 'Agents map',
      desc: 'The agents tab of the right panel: a list with details, a session tree, time lanes, cards, or a graph in an editor tab (the panel keeps the list then). Open tabs switch immediately.',
      options: {
        list: 'list — turn agents and details',
        tree: 'tree — the session as branches',
        lanes: 'lanes — a time axis',
        cards: 'cards — an agent as a card',
        graph: 'graph — an editor tab',
      },
    },
    fontInterface: {
      name: 'Interface font',
      desc: 'Reply text and settings; the sidebar too, unless a panel font is set. Empty — same as VS Code; also used if the font is not installed.',
    },
    fontPanels: {
      name: 'Panel font',
      desc: 'The header, the input box, the right and left panels. Empty — as now: the chat is monospace, the sidebar uses the interface font. Numbers, paths and code stay on the code font.',
    },
    fontAsBefore: 'as now',
    fontSamplePanels: 'New session · enter ↵',
    fontCode: {
      name: 'Code font',
      desc: 'Monospace: code, the action log in the feed, numbers. Empty — the VS Code editor font.',
    },
    fontVscode: (name: string) => (name ? `same as VS Code · ${name}` : 'same as VS Code'),
    fontSystem: 'system',
    fontOwn: 'custom font',
    fontAdd: 'Add from Google Fonts…',
    fontRemove: 'Remove downloaded font',
    fontSampleUi: 'Ticket counter 42',
    fontSampleCode: 'count ?? prev;',
    sampleTrying: (name: string) => `sample — trying ${name}`,
    sample: 'sample — fonts and size from the settings above',
    uiFontSize: {
      name: 'Interface size',
      desc: 'Everything except the feed: header, input box, panels, sidebar, this tab. The feed has its own size above. Open tabs update immediately.',
    },
    feedFontSize: {
      name: 'Feed text size',
      desc: 'The whole chat feed scales: replies, actions, code, cards. Open tabs update immediately.',
      def: 'default',
    },
    keychain: {
      name: 'Read token from macOS Keychain',
      desc: 'Needed only to request limits. Without it, percentages appear after the first turn.',
    },
    exe: {
      name: 'Path to claude',
      desc: 'Empty — look for the system one: PATH, ~/.local/bin, Homebrew.',
      placeholder: 'empty — look for the system one',
      check: 'check',
      checking: 'checking…',
      found: 'found',
      notFound: 'not found',
      source: { setting: 'from setting', system: 'system', none: '' },
    },
  },
  sidebar: {
    aria: 'Agentura sidebar',
    head: 'Agentura',
    settings: 'Agentura settings',
    gear: '⚙',
    account: 'Account and limits',
    refresh: '↻',
    refreshTitle: 'Refresh limits',
    refreshing: 'Refreshing limits…',
    updatedAt: 'data as of',
    refreshFailed: 'refresh failed',
    sessions: 'Sessions',
    listMode: {
      names: { detailed: 'detailed', compact: 'compact', dense: 'dense' },
      icons: { detailed: '☰', compact: '≡', dense: '≣' },
      title: (cur: string, next: string) => `List view: ${cur} · switch to “${next}”`,
    },
    newSession: 'New session',
    newSessionKey: '⌘⇧N',
    search: 'Search by name',
    searchFocus: 'Search by name',
    searchClear: 'Clear search (Esc)',
    noMatches: 'Nothing found.',
    fold: (name: string, folded: boolean) => `${folded ? 'Expand' : 'Collapse'}: ${name}`,
    accountLabels: { account: 'Account', plan: 'Plan', login: 'Login', agent: 'Agent' },
    agentName: 'Claude',
    unknown: '—',
    loadError: 'could not load',
    limitFive: '5-hour window',
    limitWeek: 'Week',
    limitWeekModel: (model: string) => `Week · ${model}`,
    miniFive: '5 h',
    miniWeek: 'wk',
    resetShort: (when: string) => `→ ${when}`,
    loginOk: 'signed in',
    resetAt: (when: string) => `resets ${when}`,
    resetIn: (when: string) => `in ${when}`,
    noSessions: 'No sessions in this project yet.',
    renameTitle: 'Double-click to rename',
    renameHint: 'Enter — save, Esc — cancel',
    days: { today: 'Today', yesterday: 'Yesterday' },
    now: 'now',
    ctx: 'ctx',
    partialCost: '≈ not all models',
    stateTag: {
      waiting: 'waiting for a reply',
      error: 'engine error',
      limit: 'limit reached',
    },
  },
  sessionsPopup: {
    heading: (project: string) => `${project} sessions · resume`,
    all: 'All sessions in the sidebar',
    newSession: 'New session',
    empty: 'no sessions yet',
  },
};
