import type { EffortLevel } from '../agent/types';
import { en } from './strings.en';

/**
 * Строки интерфейса webview в одном месте: русский словарь `ru` здесь, английский — `strings.en.ts`
 * (тот же тип `Ui`, расхождение ключей и сигнатур ловит компилятор). Язык берётся из `<html lang>`
 * при загрузке модуля. Данные сессий сюда не попадают.
 */
const ru = {
  hud: {
    aria: 'Сессия',
    sessions: 'sessions',
    sessionsTitle: 'Сессии',
    untitled: 'новая сессия',
  },
  tabs: { chat: 'чат', changes: 'изменения', git: 'git', agents: 'агенты' },
  panel: {
    tabsAria: 'Панель: изменения, git, агенты',
    hide: 'Скрыть панель',
    show: 'Показать панель',
    railAria: 'Свёрнутая панель',
    openTab: (name: string) => `Открыть панель: ${name}`,
    gripAria: 'Ширина панели',
    gripTitle: 'Тяни, чтобы изменить ширину; двойной клик — 300 px',
  },
  log: {
    aria: 'Лента сессии',
    diff: 'diff',
    preview: 'превью',
    open: 'открыть',
    artifactCreated: 'создан',
    artifactUpdated: 'обновлён',
    artifactPublished: 'опубликован',
    stop: 'stop · esc',
    stopOnly: 'stop',
    stopTip: 'Остановить ход',
    copy: 'copy',
    copied: 'скопировано',
    queued: 'в очереди',
    thinking: 'думает',
    answering: 'отвечает',
    waiting: 'ждёт ответа',
    waitingPlan: 'ждёт решения по плану',
    compacting: 'сжимаю контекст',
    waitingPermission: 'ждёт разрешения',
    running: (op: string) => `выполняю ${op}`,
    toolError: 'ошибка',
    toolStopped: 'остановлено',
    thinkToggle: 'Показать рассуждение целиком',
    actions: (n: number) => `${n} ${plural(n, 'действие', 'действия', 'действий')}`,
    foldLive: 'идёт',
    foldToggle: 'Показать или скрыть действия хода',
    turnLive: (t: string) => `идёт ${t}`,
    who: 'claude',
    waitingAgents: (n: number) => `ждёт ${n} ${plural(n, 'агента', 'агентов', 'агентов')}`,
    stopAll: 'stop all · esc',
    stopAllTitle: 'Остановить всех идущих субагентов сессии (Esc — прервать ход целиком)',
    imagesTokens: (k: string) => `картинки ≈${k}`,
    imagesTokensTitle:
      'Оценка по размеру картинок: ширина × высота / 750 (движок их отдельно не считает)',
    screenshot: 'скриншот',
    openImage: 'Открыть картинку во вкладке редактора',
    noImageData:
      'Транскрипт не отдал картинку (или она старше последних в истории) — только плашка',
    openFile: 'Открыть файл во вкладке редактора',
    inPath: (path: string) => `в ${path}`,
    todoWhat: 'список задач',
    askFallback: 'вопрос',
    planReady: 'план готов',
    fileNoCopy:
      'Файл вне рабочей папки, а копии в истории нет (старше последних) — откроется исходный, если он на месте',
  },
  sys: {
    compacting: 'сжимаю контекст…',
    compactedAuto: 'контекст сжат автоматически',
    compactedManual: 'контекст сжат',
    compactFailed: (error?: string) => `не удалось сжать контекст${error ? `: ${error}` : ''}`,
    interrupted: 'ход остановлен',
    tokensSuffix: ' токенов',
    closed: (reason: 'exit' | 'error' | 'disposed', message?: string) =>
      reason === 'error'
        ? `сессия оборвалась${message ? `: ${message}` : ''}`
        : reason === 'exit'
          ? 'движок завершился, сессия закрыта'
          : 'сессия закрыта',
    status: (model: string, mode: string, cwd: string) =>
      `/status · модель ${model} · режим ${mode} · ${cwd}`,
    planOn: 'режим plan включён',
    contextPassed: (used: string, threshold: string, fullAt: string) =>
      `контекст ${used}: порог ${threshold} пройден, автосжатие при ${fullAt}`,
    historyTrimmed: (n: number) =>
      `показаны последние ходы; ранее — ещё ${n} ${plural(n, 'ход', 'хода', 'ходов')}`,
    sendFailed: 'сообщение не отправлено: сессия завершена',
    modeChanged: (mode: string) => `режим: ${mode}`,
    turnNotStarted: (message: string) => `ход не начат: ${message}`,
    limitDefault: 'лимит исчерпан',
    resetAt: (time: string) => `сброс в ${time}`,
    denied: 'отклонено: ',
    alwaysRule: 'всегда: ',
    questionDeclined: 'вопрос отклонён',
    picked: (nums: number[]) =>
      nums.length === 1
        ? `выбран вариант ${nums[0]}`
        : nums.length > 1
          ? `выбраны варианты ${nums.join(', ')}`
          : 'ответ отправлен',
    customAnswer: (text: string) => `свой ответ: ${text}`,
    plan: {
      run: 'план принят · выполняю',
      'run-edits': 'план принят · выполняю, принимая правки',
      refine: 'план на доработку',
      reject: 'план отклонён',
    } as Record<string, string>,
  },
  fail: {
    titleFatal: 'Движок остановился',
    titleTurn: 'Ход не удался',
    tag: (at: string) => `${at} · ошибка`,
    codeLine: (code: string) => `код ошибки: ${code}`,
    hintNetwork:
      'Похоже на обрыв сети. Сессия сохранена: при повторе ход начнётся с этого же сообщения.',
    hintTurn: 'Сессия сохранена: при повторе ход начнётся с этого же сообщения.',
    hintIdle: 'Сессия сохранена: её можно возобновить и продолжить.',
    retryTurn: 'Повторить ход',
    retryResume: 'Возобновить сессию',
    retrying: 'повторяю…',
    missingTitle: 'Claude Code не найден',
    missingHint:
      'Установите Claude Code (https://claude.com/claude-code), выполните вход (claude → /login) или укажите путь к claude в настройках ⚙ (agentura.claudeExecutable).',
    missingSettings: 'Открыть настройки',
    missingRecheck: 'Проверить снова',
    missingChecking: 'проверяю…',
    openLog: 'Открыть журнал расширения',
    logHint: 'журнал: панель Output → Agentura',
    toolOutputTitle: 'Вывод инструмента',
    toolOutputHint: 'Полный вывод — как его увидела модель.',
    toolToggle: 'Показать вывод целиком',
    toolFailTag: 'результат инструмента',
    truncated: (n: number) => `… ещё ${n} символов обрезано`,
  },
  limit: {
    bannerFive: 'Лимит 5-часового окна исчерпан.',
    bannerWeek: 'Недельный лимит исчерпан.',
    bannerWeekModel: (model: string) => `Недельный лимит модели ${model} исчерпан.`,
    bannerGeneric: 'Лимит подписки исчерпан.',
    resetsAt: (time: string, left: string) => `Сброс в ${time}, через ${left}.`,
    resetUnknown: 'Время сброса неизвестно.',
    weekFree: (percent: number) => `Недельное окно свободно на ${percent} %.`,
    limits: 'Лимиты',
    limitsTitle: 'Открыть боковую панель с лимитами',
    retry: 'Попробовать снова',
    retryTitle: 'Снять блокировку и отправить сообщение: лимит мог сброситься',
    deferred: (time: string) => `отправка отложена до ${time}`,
    deferredUnknown: 'отправка отложена: лимит исчерпан',
    placeholder: 'лимит исчерпан — сообщение можно набрать, отправка после сброса',
  },
  cards: {
    permTitle: (tool: string) =>
      tool === 'Bash'
        ? 'Разрешить запуск команды?'
        : tool === 'Edit' || tool === 'MultiEdit'
          ? 'Разрешить правку файла?'
          : tool === 'Write'
            ? 'Разрешить запись файла?'
            : `Разрешить ${tool}?`,
    modeTag: (mode: string) => `режим ${mode}`,
    subagent: 'субагент',
    allow: 'Разрешить',
    acceptEdit: 'Принять правку',
    alwaysFor: 'Всегда для',
    alwaysDirs: 'Всегда для папки',
    acceptEditsSession: 'Принимать правки до конца сессии',
    deny: 'Отклонить',
    sent: 'ответ отправлен…',
    enter: 'enter',
    esc: 'esc',
    destination: (d?: string): string =>
      d === 'localSettings'
        ? '.claude/settings.local.json'
        : d === 'projectSettings'
          ? '.claude/settings.json'
          : d === 'userSettings'
            ? '~/.claude/settings.json'
            : 'эта сессия',
    alwaysHint: (where: string) => `«всегда» пишется в ${where}`,
    sessionHint: '«всегда» — до конца сессии',
    plusDirs: (dir: string, more: number) =>
      ` · и папка ${dir}${more > 0 ? ` +${more}` : ''} до конца сессии`,
    editsHint: '«принимать правки» = режим acceptEdits',
    workdir: (dir: string) => `рабочая папка ${dir}`,
    blocked: (path: string) => `вне разрешённых папок: ${path}`,
    openDiff: 'открыть дифф',
    newFile: 'новый файл',
    diffNote: 'Полный дифф открывается в редакторе VS Code.',
    fragmentNote: 'Фрагмент не найден в файле на диске — показана сама правка.',
    tooLarge: 'Дифф слишком большой для превью — откройте его в редакторе.',
    moreLines: (n: number) =>
      `… ещё ${n} ${plural(n, 'строка', 'строки', 'строк')} — в полном диффе`,
    previewLoading: 'готовлю превью…',
    question: 'вопрос агента',
    questionAnswered: 'вопрос агента · отвечен',
    questionDeclined: 'вопрос агента · отклонён',
    questionCancelled: 'вопрос агента · отменён',
    multi: 'можно несколько',
    custom: 'Свой вариант',
    customHint: 'напишу в поле ввода',
    submit: 'Ответить',
    planTitle: 'План',
    planTag: (steps: number, files: number) =>
      [
        steps ? `${steps} ${plural(steps, 'шаг', 'шага', 'шагов')}` : '',
        files ? `${files} ${plural(files, 'файл', 'файла', 'файлов')}` : '',
      ]
        .filter(Boolean)
        .join(' · ') || 'план',
    planDone: {
      run: 'план · принят',
      'run-edits': 'план · принят, правки без вопросов',
      refine: 'план · на доработке',
      reject: 'план · отклонён',
    } as Record<string, string>,
    planCancelled: 'план · отменён',
    run: 'Выполнять',
    runEdits: 'Выполнять, принимая правки',
    refine: 'Доработать план',
    reject: 'Отклонить',
    planFileNew: 'новый',
    planFileEdit: 'правка',
  },
  reply: {
    question: 'свой ответ на вопрос агента — enter · esc — отмена',
    plan: 'что доработать в плане — enter · esc — отмена',
    waiting: 'ответ агенту или новая задача — уйдёт после решения по запросу',
  },
  empty: {
    title: (project: string) => `Новая сессия в ${project}`,
    lead: 'Опишите задачу или задайте вопрос. Агент видит открытый файл и выделение — снять можно крестиком у поля ввода.',
    tips: [
      ['@', 'файлы и папки проекта'],
      ['/', 'команды и скиллы: /plan, /compact, /status'],
      ['shift+enter', 'перенос строки'],
      ['esc', 'остановить ход'],
      ['↑', 'прошлые сообщения'],
    ] as const,
    recent: 'недавние сессии',
    newSession: 'новая сессия',
    turns: (n: number) => `${n} ${plural(n, 'ход', 'хода', 'ходов')}`,
    waiting: 'ждёт ответа',
  },
  agents: {
    heading: 'агенты',
    stopTitle: 'Остановить',
    empty: 'пока пусто',
    main: 'основной',
    waitingTask: 'ждёт задачу',
    answering: 'отвечает',
    background: 'фоновая задача',
    done: 'готово',
    failed: 'ошибка',
    stopped: 'остановлено',
    totalCost: 'за сессию',
    /** Итог без ходов с моделью без цены (этап 5 roadmap 0.2). */
    costPartial: '≈ без части ходов',
    totalTurns: 'ходов',
    totalTime: 'время',
    totalCache: 'кэш-попадания',
    // этап 2 roadmap 0.2 (A6): группа в ленте, карта «список + детали»
    waitingAgents: 'ждёт агентов',
    turnDone: 'ход завершён',
    running: 'идёт',
    tasks: 'фоновые задачи',
    bar: 'токены хода по агентам',
    turnTokens: 'субагенты за ход',
    shell: 'shell',
    finishedAt: (time: string) => `завершён ${time}`,
    starting: 'запускается',
    thinking: 'думает',
    writing: 'пишет итог',
    nthCall: (n: number) => `${n}-й вызов`,
    doneIn: (d: string) => `готово за ${d}`,
    group: {
      parallel: (n: number) => `×${n} параллельно`,
      single: 'субагент',
      running: (n: number) => `${n} ${plural(n, 'идёт', 'идут', 'идут')}`,
      done: (n: number) => `${n} готово`,
      failed: (n: number) => `${n} ${plural(n, 'ошибка', 'ошибки', 'ошибок')}`,
      stopped: (n: number) => `${n} остановлено`,
      tokens: 'ток',
      background: 'фоном',
      map: 'карта агентов',
      waiting: 'основной ждёт агентов',
      collapse: 'свернуть',
      summary: 'итог',
      log: 'лог',
      stop: 'Остановить агента',
      more: (n: number) => ` +${n}`,
    },
    // roadmap 11: виды вкладки (дерево, дорожки, карточки)
    view: {
      scopeAria: 'Охват',
      scopeTurn: (n: number) => `ход ${n}`,
      scopeTurnNone: 'ход',
      scopeSession: 'сессия',
      graph: '↗ граф',
      graphTitle: 'Открыть граф агентов во вкладке редактора',
      empty: 'Агентов в этой сессии пока не было',
      turnTitle: (n: number) => `ход ${n}`,
      toggleTurn: 'Показать или скрыть ход',
      live: (d: string) => `идёт ${d}`,
      done: 'завершён',
      agentsTokens: 'агенты',
      mainAt: (ctx: string) => `контекст ${ctx}`,
      promptLabel: (est: string) => `промпт от основного · ${est}`,
      summaryLabel: (est: string) => `итог · ${est}`,
      errorLabel: 'ошибка',
      callsLabel: (n: number) => `последние вызовы · ${n}`,
      estTip: 'оценка по длине текста',
      transcript: 'транскрипт',
      log: 'лог',
      stop: 'остановить',
      stopShort: '■ стоп',
      calls: (n: number) => `${n} ${plural(n, 'вызов', 'вызова', 'вызовов')}`,
      resultToMain: (est: string) => `итог ${est} → в основной`,
      bg: 'фоном',
      sinceTurn: (n: number) => `с хода ${n}`,
      shellKind: 'shell',
      before: '↤ раньше оси',
      axisAria: 'Ось времени хода',
      nowAria: 'сейчас',
      wait: 'ждёт агентов',
      counts: {
        running: (n: number) => `${n} ${plural(n, 'идёт', 'идут', 'идут')}`,
        ok: (n: number) => `${n} готово`,
        err: (n: number) => `${n} ${plural(n, 'ошибка', 'ошибки', 'ошибок')}`,
        stop: (n: number) => `${n} остановлено`,
      },
    },
    // roadmap 11, этап 2: граф агентов во вкладке редактора
    graph: {
      aria: 'Граф агентов',
      turn: 'ход',
      turnsAria: 'Ходы с агентами',
      live: 'идёт',
      agentsTotal: 'агенты',
      context: (used: string, limit: string) => `контекст ${used} / ${limit}`,
      returned: (est: string) => `вернулось итогов: ${est}`,
      edgeTip: '↗ промпт агенту (оценка по длине) · ↙ итог в основной',
      legendUp: '↗ промпт агенту',
      legendDown: '↙ итог в основной',
      legendBg: 'пунктир — фон',
      summaryPending: 'итог · появится, когда агент закончит',
      waiting: 'Ждём данные из вкладки чата — если она скрыта, откройте её.',
      pick: 'Выберите агента на графе',
      detailAria: 'Выбранный агент',
    },
    detail: {
      prompt: 'промпт от основного',
      summary: 'итог агенту основному',
      error: 'ошибка',
      stoppedNote: 'агент остановлен',
      timeline: (n: number) => `ход агента · ${n} ${plural(n, 'вызов', 'вызова', 'вызовов')}`,
      more: (n: number) => `ещё ${n} ${plural(n, 'строка', 'строки', 'строк')}`,
      empty: 'вызовов пока нет',
      text: 'текст',
      transcript: 'транскрипт',
      transcriptTitle: 'Открыть транскрипт агента только для чтения',
      stop: 'остановить',
      tokens: 'токены',
      calls: 'вызовов',
      live: (d: string) => `◐ идёт ${d}`,
      ok: (d: string) => `✓ готово за ${d}`,
      err: (d: string) => `✕ ошибка · ${d}`,
      stopped: (d: string) => `■ остановлено · ${d}`,
    },
  },
  changes: {
    scopeAria: 'Охват',
    session: 'сессия',
    turn: (n: number) => `ход ${n}`,
    files: (n: number) => plural(n, 'файл', 'файла', 'файлов'),
    diffAll: 'дифф всего',
    diffAllTitle: 'Открыть дифф всех изменённых файлов',
    fileTitle: 'Открыть дифф файла',
    root: './',
    newFile: 'новый',
    checks: 'проверки',
    emptySession: 'Агент пока ничего не менял',
    emptyTurn: 'В этом ходе правок нет',
    turnTitle: (n: number) => `Ход ${n}`,
  },
  git: {
    loading: 'git загружается…',
    none: 'Репозиториев нет',
    noneHint:
      'VS Code ищет репозитории на глубину git.repositoryScanMaxDepth (по умолчанию 1); откройте папку репозитория или поднимите значение.',
    unavailable: 'git недоступен',
    changes: (n: number) => `${n} ${plural(n, 'изменение', 'изменения', 'изменений')}`,
    repos: (n: number) => `${n} ${plural(n, 'репозиторий', 'репозитория', 'репозиториев')}`,
    agentChip: (n: number) => `агент ${n}`,
    agentChipTitle: 'Показать только файлы, которые правил агент',
    modeAria: 'Вид списка',
    modePath: 'путь',
    modeTree: 'дерево',
    unstaged: 'неиндексированные',
    staged: 'в индексе',
    stageAll: '+ все в индекс',
    unstageAll: '− все',
    emptyUnstaged: 'нет',
    emptyStaged: 'пусто — «+» у файла',
    emptyAgent: 'нет файлов агента',
    clean: 'чисто',
    recent: 'последние коммиты',
    branchTitle: 'Сменить ветку',
    unpublished: 'не опубликована',
    unpublishedShort: 'новая',
    unpublishedTitle: 'Ветки нет в origin — push её опубликует',
    syncTitle: (up: string) => `Против ${up}`,
    fetch: 'Fetch',
    pull: 'Pull',
    push: 'Push',
    publish: 'Опубликовать ветку',
    agentDot: 'Правил агент в этой сессии',
    openFile: 'Открыть файл',
    discard: 'Отменить изменения',
    stage: 'В индекс',
    unstage: 'Убрать из индекса',
    openDiff: 'Открыть дифф',
    renamedFrom: (from: string) => `из ${from}`,
    binary: 'bin',
    statusTitle: {
      M: 'изменён',
      A: 'добавлен',
      D: 'удалён',
      R: 'переименован',
      U: 'не отслеживается',
      C: 'конфликт',
      T: 'тип изменён',
    },
    op: { merge: 'идёт merge', rebase: 'идёт rebase' },
    summaryPlaceholder: 'Сообщение коммита',
    summaryAria: 'Заголовок коммита',
    descPlaceholder: 'Описание',
    descAria: 'Описание коммита',
    generate: 'Сообщение пишет агент по индексу',
    generating: 'Агент пишет сообщение…',
    amend: 'amend',
    andPush: 'и push',
    commit: 'Коммит',
    filesN: (n: number) => `${n} ${plural(n, 'файл', 'файла', 'файлов')}`,
    commitAmend: 'Amend',
    commitHint: '⌘/Ctrl+Enter',
    needStage: 'Сначала в индекс',
    needMessage: 'Введите заголовок коммита',
    busy: 'Идёт операция…',
    more: 'Ещё',
    commitPush: 'Коммит и push',
    commitAll: 'Коммит всех изменений',
    errorClose: 'Скрыть',
    errorOp: (op: string, message: string) => `${op}: ${message}`,
    openRepo: 'Открыть репозиторий…',
    commitCompact: 'Коммит',
    targetsLabel: 'в',
    targetsAria: 'В какие репозитории коммитить',
    commitTo: (n: number) => `Коммит в ${n} ${plural(n, 'репозиторий', 'репозитория', 'репозиториев')}`,
    needTarget: 'Отметьте репозиторий с файлами в индексе',
    committed: (names: string) => `Закоммичено: ${names}`,
    repoPick: 'Репозитории',
    cleanHeading: 'чистые',
    fetchAll: 'Fetch во всех',
  },
  compose: {
    mode: 'режим',
    model: 'модель',
    effort: 'effort',
    agent: 'агент',
    agentTitle: 'Агент: Claude · Codex, Gemini — скоро',
    context: 'контекст',
    compact: 'сжать',
    ctxTitle: (thresholds: string[], fullAt: string, scale?: string) =>
      `Контекст: пороги ${thresholds.join(' ')}, автосжатие при ${fullAt}${scale ? ` · шкала до ${scale}` : ''}`,
    thresholdPassed: (k: string) => `порог ${k} пройден`,
    cache: 'кэш',
    cacheExpired: 'истёк',
    cacheTitle: (ttl: string) => `Кэш промпта: живёт ${ttl} после последнего ответа`,
    fiveHour: '5ч',
    fiveHourWindow: '5-часовое окно',
    week: 'неделя',
    weekShort: 'нед',
    limitsUnknown: 'Лимиты подписки пока не получены',
    send: 'enter ↵',
    sendTitle: 'Отправить',
    queue: '↵ в очередь',
    stopTitle: 'Остановить',
    stopKey: 'esc',
    placeholder: 'задача, @файл, /команда',
    closedPlaceholder: 'сессия завершена — начните новую через «+ Новая сессия» в боковой панели',
    plus: '+',
    plusTitle: 'Добавить контекст',
    plusFile: '+ файл',
    sendLong: 'отправить ↵',
    cheatsheet: '/ команды · @ файл',
    engineTitle: 'Агент, модель и effort',
    removeChip: 'Убрать из контекста',
    autoFile: 'открыт',
    autoSelection: 'выделение',
    historyPos: (i: number, n: number) => `${i} из ${n}`,
    historyNote: '· ↑ старше · ↓ новее · esc — очистить',
    historyLabel: 'история',
    agentMenu: 'агент',
    agentReady: 'готов',
    claudeVia: (version?: string) =>
      `через Claude Agent SDK${version ? ` · claude ${version}` : ''}`,
    acpAdapter: 'адаптер по форме ACP',
    agentSoon: 'скоро',
    imagesHint: '⌘V — вставить картинку · перетащить с ⇧',
    imagesPlus: (k: string) => `+${k} картинки`,
    imagesPlusTitle: 'Картинки считаются по размеру: ширина × высота / 750 токенов',
    imageName: (n: number) => `скриншот ${n}`,
    imageBusy: 'уменьшаю…',
    imageScaled: (w: number, h: number) => `уменьшен с ${w}×${h}`,
    imageRemove: 'Убрать',
    imageFormats: 'поддерживаются png, jpeg, gif, webp',
    imageProblem: {
      format: (ext: string) => `${ext || 'формат'} не берём`,
      size: 'больше 5 МБ',
      count: 'не больше 10 картинок',
      total: 'сообщение больше 20 МБ',
      read: 'не прочитать',
      session: 'сессия: вложений больше 24 МБ — начните новую',
      context: 'не поместится в окно модели',
    },
    imageProblemTitle: {
      format: 'поддерживаются png, jpeg, gif, webp',
      size: 'после уменьшения до 1568 px картинка всё ещё больше 5 МБ base64',
      count: 'в одном сообщении — до 10 картинок',
      total: 'картинки одного сообщения — до 20 МБ base64 вместе (лимит запроса к API — 32 МБ)',
      read: 'файл не прочитан или повреждён',
      session:
        'Лимит запроса к API — 32 МБ, а в каждый запрос уходит вся история с её вложениями: в сессии их уже слишком много. «Сжать» убирает старые вложения из запросов, новая сессия начинает с нуля',
      context:
        'Вложения сообщения могут занять не больше 70 % свободного окна контекста; «сжать» освободит место',
    },
    filesHint: 'перетащить с ⇧ — файл из проводника VS Code',
    filesPlus: (k: string) => `+${k} файлы`,
    filesPlusTitle: 'Оценка: текст — символы / 4, pdf — около 1 500 токенов на страницу',
    fileUnknownTokens: '≈?',
    fileProblem: {
      binary: 'двоичный файл не берём',
      size: 'слишком большой',
      empty: 'пустой файл',
      folder: 'папки не берём',
      pages: 'больше 100 страниц',
      read: 'не прочитать',
      count: 'не больше 10 файлов',
      total: 'сообщение больше 20 МБ',
      foreign: 'не картинка — через «+»',
      pdf: 'pdf не читается',
      sessionPages: 'сессия: pdf больше 100 страниц — начните новую',
      session: 'сессия: вложений больше 24 МБ — начните новую',
      context: 'не поместится в окно модели',
    },
    fileProblemTitle: {
      binary: 'берём текст в UTF-8 (без NUL-байтов), pdf и картинки png, jpeg, gif, webp',
      size: 'текст — до 256 КБ, pdf — до 15 МБ, любой файл — до 30 МБ',
      empty: 'в файле нет текста',
      folder: 'перетащите файлы из папки, а не её саму',
      pages: 'API принимает pdf до 100 страниц',
      read: 'файл не прочитан',
      count: 'в одном сообщении — до 10 файлов',
      total: 'картинки и файлы одного сообщения — до 20 МБ вместе (лимит запроса к API — 32 МБ)',
      foreign:
        'Не из VS Code перетаскиваются только картинки: текст и pdf добавьте через «+» или перетащите из проводника VS Code',
      pdf: 'pdf зашифрован, повреждён или в нём не найти страниц — API такой не примет, а отказ остался бы в сессии',
      sessionPages:
        'Лимит API — 100 страниц pdf на запрос, а в каждый запрос уходит вся история сессии: с этим pdf их стало бы больше. «Сжать» убирает старые вложения из запросов, новая сессия начинает с нуля',
      session:
        'Лимит запроса к API — 32 МБ, а в каждый запрос уходит вся история с её вложениями: в сессии их уже слишком много. «Сжать» убирает старые вложения из запросов, новая сессия начинает с нуля',
      context:
        'Вложения сообщения могут занять не больше 70 % свободного окна контекста (текст — символы / 4, pdf — около 1 500 токенов на страницу); «сжать» освободит место',
    },
  },
  menus: {
    commands: 'команды',
    skills: 'скиллы проекта',
    files: 'файлы и папки',
    noFiles: 'ничего не найдено',
    fileHint: 'файл',
    folderHint: 'папка',
    skillHint: 'skill',
    addContext: 'добавить контекст',
    pickFile: 'Файл или папка…',
    pickFileHint: '@',
    openFile: 'Открытый файл',
    selection: 'Выделение в редакторе',
    autoOn: 'добавляется автоматически',
    autoOff: 'не добавляется',
    image: 'Изображение или файл…',
    imageSmall: 'текст, pdf, картинка · ⌘V — скриншот, перетащить с ⇧',
    imageHint: '⌘V',
    mode: 'режим',
    model: 'модель',
    effort: 'effort',
    thinking: 'extended thinking',
    thinkingHint: 'показывать блоки think в ленте',
    byDefault: 'по умолчанию',
    bypassOff: 'включается настройкой agentura.allowBypassPermissions',
    modelDesc: {
      opus: 'сложные задачи, планирование',
      sonnet: 'быстрее и дешевле',
      haiku: 'мелкие правки',
    },
  },
  commands: {
    plan: ['перейти в режим плана', 'режим'],
    compact: ['сжать контекст сейчас', 'контекст'],
    clear: ['новый диалог', '⌘N'],
    status: ['аккаунт, вход, модель', ''],
  } as Record<string, readonly [string, string]>,
  modes: {
    default: ['manual', 'спрашивать перед правками и командами', ''],
    acceptEdits: [
      'принимать правки',
      'правки файлов без вопросов, команды — с вопросом',
      'acceptEdits',
    ],
    plan: ['plan', 'только читать и планировать', '/plan'],
    bypassPermissions: ['без разрешений', 'без вопросов вообще', 'bypass'],
  } as Record<string, readonly [string, string, string]>,
  efforts: ['low', 'medium', 'high', 'xhigh', 'max'] as const,
  /** Даты и длительности: названия дней и месяцев, порядок «число месяц», предлоги. */
  time: {
    weekdaysShort: ['вс', 'пн', 'вт', 'ср', 'чт', 'пт', 'сб'],
    /** После «в »: `в четверг`. */
    weekdaysLong: [
      'воскресенье',
      'понедельник',
      'вторник',
      'среду',
      'четверг',
      'пятницу',
      'субботу',
    ],
    months: [
      'января',
      'февраля',
      'марта',
      'апреля',
      'мая',
      'июня',
      'июля',
      'августа',
      'сентября',
      'октября',
      'ноября',
      'декабря',
    ],
    /** `23 сентября`, с годом — `23 сентября 2025`. */
    dayMonth: (day: number, month: number, year?: number): string =>
      `${day} ${ru.time.months[month]}${year !== undefined ? ` ${year}` : ''}`,
    lessThanMinute: 'меньше минуты',
    minutes: (n: number) => `${n} мин`,
    hourMinutes: (h: number, mm: string) => `${h} ч ${mm} мин`,
    daysHours: (d: number, h: number) => `${d} дн ${h} ч`,
    oneHour: '1 ч',
    at: (clock: string) => `в ${clock}`,
    atWeekday: (weekday: string, clock: string) => `в ${weekday}, ${clock}`,
    atDate: (date: string, clock: string) => `${date}, ${clock}`,
  },
  settings: {
    title: 'Настройки',
    head: 'Agentura · настройки',
    aria: 'Настройки',
    openUi: 'в настройках VS Code',
    openUiTitle: 'Открыть в настройках VS Code',
    openJson: 'settings.json',
    openJsonTitle: 'Открыть settings.json',
    openJsonLink: 'открыть settings.json',
    navAria: 'Разделы настроек',
    sections: {
      session: 'Новая сессия',
      limits: 'Контекст и лимиты',
      sidebar: 'Боковая панель',
      look: 'Внешний вид',
      engine: 'Движок',
    },
    source:
      'Хранится в настройках VS Code, раздел «Пользователь». Меняется сразу, без перезапуска.',
    isNew: 'новая',
    machineOnly: 'только эта машина',
    overridden:
      'В настройках рабочей папки это значение переопределено — здесь правится пользовательское, эффект будет после удаления переопределения.',
    mode: {
      name: 'Режим новых сессий',
      desc: 'С каким режимом открывается новая сессия. В открытой сессии режим меняется меню «режим» под полем ввода или ⇧⇥.',
      options: {
        manual: 'manual',
        acceptEdits: 'acceptEdits',
        plan: 'plan',
        bypassPermissions: 'без разрешений',
      } as Record<string, string>,
    },
    bypass: {
      name: 'Разрешить режим «без разрешений»',
      desc: 'Добавляет пункт «без разрешений» (bypassPermissions) в меню режима. Сам режим не включается — его выбирают в сессии.',
      warnTitle: 'Без разрешений',
      warn: ' агент правит файлы и запускает любые команды, не спрашивая, — включая удаление и сеть. Включай для изолированной папки или контейнера; на рабочем проекте лучше режим «принимать правки».',
    },
    model: {
      name: 'Модель по умолчанию',
      desc: 'Для новых сессий. Пусто — та, что стоит в Claude Code (выбор движка).',
      placeholder: 'выбор движка',
    },
    effort: {
      name: 'Effort по умолчанию',
      desc: 'Сколько думать перед ответом. Меняется в строке под полем ввода.',
      engine: 'выбор движка',
    },
    thresholds: {
      name: 'Пороги шкалы контекста',
      desc: 'Где полоса и число над полем ввода становятся жёлтыми и оранжевыми. Автосжатие на 200 000 делает движок — здесь не настраивается.',
      yellow: 'жёлтый',
      orange: 'оранжевый',
      compress: '200k · сжатие',
    },
    poll: {
      name: 'Опрашивать лимиты каждые',
      desc: '5-часовое и недельное окно в боковой панели и под полем ввода. Вручную — ↻ в боковой панели.',
      noLess: 'не меньше 5',
      unit: 'мин',
    },
    listView: {
      name: 'Вид списка сессий',
      desc: 'Сколько строк на сессию в боковой панели. Ходы и цена всегда есть в подсказке строки. Переключается и кнопкой в заголовке «Сессии».',
      options: {
        detailed: 'подробно — две строки',
        compact: 'компактно — две строки только у важных',
        dense: 'плотно — всё в одну строку',
      } as Record<string, string>,
    },
    listContext: {
      name: 'Контекст в строке',
      desc: 'Колонка справа: контекст последнего запроса сессии, например 173k ctx.',
    },
    listTime: {
      name: 'Время в строке',
      desc: 'Колонка справа: когда сессия обновлялась — сейчас, 13:05, вт, 25.09.',
    },
    language: {
      name: 'Язык интерфейса',
      desc: 'Применяется после перезагрузки окна VS Code. «Как в VS Code» — русский при русском интерфейсе VS Code, иначе английский. Названия команд и описания настроек всегда следуют языку VS Code.',
      options: {
        auto: 'Как в VS Code',
        ru: 'Русский',
        en: 'English',
      } as Record<string, string>,
    },
    sidebarTop: {
      name: 'Верх боковой панели',
      desc: 'Сколько места под аккаунтом и лимитами: подробно — таблицей, компактно — по строке, плотно — мини-шкалы лимитов в заголовке панели.',
      options: {
        detailed: 'подробно — как раньше',
        compact: 'компактно — аккаунт и лимиты по строке',
        dense: 'плотно — лимиты в заголовке панели',
      } as Record<string, string>,
    },
    feedStyle: {
      name: 'Вид ленты чата',
      desc: 'Как выглядит ход: журнал — плоский список, свёрнуто — действия завершённых ходов в одну строку, реплики — пузырь и чипы действий, карточки — ход рамкой с лентой действий. Открытые вкладки меняют вид сразу.',
      options: {
        journal: 'журнал — как раньше',
        folded: 'свёрнуто — действия в одну строку',
        replies: 'реплики — пузырь и чипы',
        cards: 'карточки — ход рамкой',
      } as Record<string, string>,
    },
    agentsView: {
      name: 'Карта агентов',
      desc: 'Вкладка «агенты» правой панели: список с деталями, дерево сессии, дорожки времени, карточки или граф во вкладке редактора (в панели при нём остаётся список). Открытые вкладки меняют вид сразу.',
      options: {
        list: 'список — агенты хода и детали',
        tree: 'дерево — сессия ветками',
        lanes: 'дорожки — ось времени',
        cards: 'карточки — агент карточкой',
        graph: 'граф — вкладка редактора',
      } as Record<string, string>,
    },
    gitLayout: {
      name: 'Вкладка git: несколько репозиториев',
      desc: 'Вкладка git, когда в рабочей папке несколько репозиториев (один репозиторий от настройки не зависит): стопка разделов, выбор репозитория сверху или общий список с одним коммитом в несколько репо. Открытые вкладки меняют раскладку сразу.',
      options: {
        stack: 'стопка — раздел на репозиторий',
        picker: 'выбор — по одному репозиторию',
        unified: 'общий список — один коммит',
      } as Record<string, string>,
    },
    fontInterface: {
      name: 'Шрифт интерфейса',
      desc: 'Текст ответов и настройки; боковая панель — тоже, пока не задан шрифт панелей. Пусто — как в VS Code; шрифта нет в системе — тоже.',
    },
    fontPanels: {
      name: 'Шрифт панелей',
      desc: 'Шапка, поле ввода, правая и левая панели. Пусто — как сейчас: чат моноширинный, боковая панель — шрифтом интерфейса. Числа, пути и код остаются на шрифте кода.',
    },
    fontAsBefore: 'как сейчас',
    fontSamplePanels: 'Новая сессия · enter ↵',
    fontCode: {
      name: 'Шрифт кода',
      desc: 'Моноширинный: код, журнал действий в ленте, цифры. Пусто — шрифт редактора VS Code.',
    },
    fontVscode: (name: string) => (name ? `как в VS Code · ${name}` : 'как в VS Code'),
    fontSystem: 'системный',
    fontOwn: 'свой шрифт',
    fontAdd: 'Добавить из Google Fonts…',
    fontRemove: 'Удалить скачанный шрифт',
    fontSampleUi: 'Счётчик талонов 42',
    fontSampleCode: 'count ?? prev;',
    sampleTrying: (name: string) => `образец — примеряю ${name}`,
    sample: 'образец — шрифты и размер из настроек выше',
    uiFontSize: {
      name: 'Размер интерфейса',
      desc: 'Всё, кроме ленты: шапка, поле ввода, панели, боковая панель, эта вкладка. У ленты — свой размер выше. Открытые вкладки меняются сразу.',
    },
    feedFontSize: {
      name: 'Размер текста ленты',
      desc: 'Лента чата масштабируется целиком: ответы, действия, код, карточки. Открытые вкладки меняются сразу.',
      def: 'по умолчанию',
    },
    keychain: {
      name: 'Читать токен из Keychain macOS',
      desc: 'Нужен только для запроса лимитов. Без него проценты появятся после первого хода.',
    },
    exe: {
      name: 'Путь к claude',
      desc: 'Пусто — искать системный: PATH, ~/.local/bin, Homebrew.',
      placeholder: 'пусто — искать системный',
      check: 'проверить',
      checking: 'проверяю…',
      found: 'найден',
      notFound: 'не найден',
      source: { setting: 'из настройки', system: 'system', none: '' } as Record<string, string>,
    },
  },
  sidebar: {
    aria: 'Боковая панель Agentura',
    head: 'Agentura',
    settings: 'Настройки Agentura',
    gear: '⚙',
    account: 'Аккаунт и лимиты',
    refresh: '↻',
    refreshTitle: 'Обновить лимиты',
    refreshing: 'Обновляю лимиты…',
    updatedAt: 'данные на',
    refreshFailed: 'не обновилось',
    sessions: 'Сессии',
    listMode: {
      names: { detailed: 'подробно', compact: 'компактно', dense: 'плотно' },
      icons: { detailed: '☰', compact: '≡', dense: '≣' },
      title: (cur: string, next: string) => `Вид списка: ${cur} · переключить на «${next}»`,
    },
    newSession: 'Новая сессия',
    newSessionKey: '⌘⇧N',
    search: 'Поиск по названию',
    searchFocus: 'Поиск по названию',
    searchClear: 'Сбросить поиск (Esc)',
    noMatches: 'Ничего не найдено.',
    fold: (name: string, folded: boolean) => `${folded ? 'Развернуть' : 'Свернуть'}: ${name}`,
    accountLabels: { account: 'Аккаунт', plan: 'План', login: 'Вход', agent: 'Агент' },
    agentName: 'Claude',
    unknown: '—',
    loadError: 'не удалось получить',
    limitFive: 'Окно 5 часов',
    limitWeek: 'Неделя',
    limitWeekModel: (model: string) => `Неделя · ${model}`,
    miniFive: '5 ч',
    miniWeek: 'нед',
    resetShort: (when: string) => `→ ${when}`,
    loginOk: 'вход в порядке',
    resetAt: (when: string) => `сброс ${when}`,
    resetIn: (when: string) => `через ${when}`,
    noSessions: 'В этом проекте пока нет сессий.',
    renameTitle: 'Двойной клик — переименовать',
    renameHint: 'Enter — сохранить, Esc — отмена',
    days: { today: 'Сегодня', yesterday: 'Вчера' },
    now: 'сейчас',
    ctx: 'ctx',
    partialCost: '≈ не все модели',
    stateTag: {
      waiting: 'ждёт ответа',
      error: 'ошибка движка',
      limit: 'лимит исчерпан',
    },
  },
  sessionsPopup: {
    heading: (project: string) => `сессии ${project} · возобновить`,
    all: 'Все сессии в боковой панели',
    newSession: 'Новая сессия',
    empty: 'пока нет сессий',
  },
} as const;

/** Тип словаря: строки — `string`, не литералы, функции и кортежи сохраняют сигнатуры. */
type Widen<T> = T extends string
  ? string
  : T extends (...args: never[]) => unknown
    ? T
    : T extends readonly unknown[]
      ? { readonly [K in keyof T]: Widen<T[K]> }
      : T extends object
        ? { [K in keyof T]: Widen<T[K]> }
        : T;
export type Ui = Omit<Widen<typeof ru>, 'efforts'> & { readonly efforts: readonly EffortLevel[] };

function plural(n: number, one: string, few: string, many: string): string {
  const m10 = n % 10;
  const m100 = n % 100;
  if (m10 === 1 && m100 !== 11) return one;
  if (m10 >= 2 && m10 <= 4 && (m100 < 12 || m100 > 14)) return few;
  return many;
}

/** Язык оболочки: `<html lang>` задаёт хост (`buildWebviewHtml`); без атрибута (тесты, jsdom) — русский. */
function pickLang(): 'ru' | 'en' {
  if (typeof document === 'undefined') return 'ru';
  return document.documentElement.lang === 'en' ? 'en' : 'ru';
}

export const uiLang: 'ru' | 'en' = pickLang();
export const ui: Ui = uiLang === 'en' ? en : (ru as Ui);
