/** Строки интерфейса webview в одном месте — под будущую локализацию. Данные сессий сюда не попадают. */
export const ui = {
  hud: {
    aria: 'Сессия',
    sessions: 'sessions',
    sessionsTitle: 'Сессии',
    newChat: 'new',
    newChatTitle: 'Новый диалог',
  },
  tabs: { chat: 'чат', turn: 'ход', agents: 'агенты' },
  log: { diff: 'diff', stop: 'stop · esc' },
  agents: { heading: 'агенты', stopTitle: 'Остановить' },
  compose: {
    mode: 'режим',
    model: 'модель',
    effort: 'effort',
    agent: 'агент',
    agentTitle: 'Агент: Claude · Codex, Gemini — скоро',
    context: 'контекст',
    compact: 'сжать',
    ctxTitle: 'Контекст: пороги 120k 150k, автосжатие при 200k',
    cache: 'кэш',
    fiveHour: '5ч',
    fiveHourTitle: (reset: string) => `5-часовое окно · сброс ${reset}`,
    send: 'enter ↵',
    sendTitle: 'Отправить (Enter)',
  },
  sidebar: {
    aria: 'Боковая панель Agentura',
    head: 'Agentura',
    account: 'Аккаунт и лимиты',
    status: '/status',
    refresh: '↻',
    refreshTitle: 'Обновить лимиты',
    refreshing: 'Обновляю лимиты…',
    updatedAt: 'данные на',
    refreshFailed: 'не обновилось',
    sessions: 'Сессии',
    newSession: 'Новая сессия',
    newSessionKey: '⌘⇧N',
    search: 'Поиск по названию — скоро',
    filterTitle: 'Фильтр',
  },
} as const;
